### ISSUE TITLE
Execution of pipeline with security devops -task fails if Node6 tasks disabled 

### ISSUE THREAD

**Issue by JanneRantala** [microsoft/security-devops-azdevops#44]
Our organization has "Disable Node6 tasks" turned on for security reasons at organization level. With this turned on, pipeline won't even start execution because of an error which says

"The pipeline is not valid. Job Job: Step 'MicrosoftSecurityDevOps' references task 'MicrosoftSecurityDevOps' at version '1.6.0' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator."

**Comment by dotpaul** [comment]
Should be fixed with #34; please let @davidknise know if not

**Comment by JanneRantala** [comment]
@davidknise This is still an issue in version 1.7.1

The pipeline is not valid. Job Job: Step 'MicrosoftSecurityDevOps' references task 'MicrosoftSecurityDevOps' at version '1.7.1' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator.

**Comment by JanneRantala** [comment]
When we could expect a fix for this, @dotpaul @davidknise?

**Comment by koesper** [comment]
Still an issue, in 1.10.0 ?

**Comment by JanneRantala** [comment]
> Still an issue, in 1.10.0 ?

Yes:

"The pipeline is not valid. Job Job: Step 'MicrosoftSecurityDevOps' references task 'MicrosoftSecurityDevOps' at version '1.10.0' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator."

**Comment by JanneRantala** [comment]
Could someone from Microsoft give some estimate when this would be fixed? @dotpaul? @davidknise? Someone? After several months this is still an issue and currently blocks our use of this feature.

**Comment by yo1-markenstein** [comment]
With version 1.11.1 the issue still exist. Can't use this task in our organization.
Note that nodejs 6 is disabled for security reasons (should be of interest for a security scan task)

**Comment by reynoldsa** [comment]
Looking into this. We have a theory.

**Comment by reynoldsa** [comment]
This should be fixed now. Please try any failing pipelines again. I will close this issue in a week if there are no further reports.

**Comment by rantalajanne** [comment]
Can confirm, it's working now. Thanks, @reynoldsa & others!

**Comment by yo1-markenstein** [comment]
Awesome, working here too. 👌
Thanks @reynoldsa
